### ISSUE TITLE
Where is the "rendering_script" folder?

### ISSUE THREAD

**Issue by Zhangjzh** [kcyt/SPIFu#1]
There is a piece of instruction 'Put the "THuman2.0_Release" folder inside the "rendering_script" folder'. However, I didn't find the "rendering_script" folder.

**Comment by kcyt** [comment]
Hi, thank for your comment! The folder was from the IntegratedPIFu repository, but I uploaded the folder to this repository as well.

**Comment by Zhangjzh** [comment]
Thank you for you reply! When I tried to run the RBS algorithm, I ran into the problem 'ValueError: Unknown model type models, exiting!'. Do you have any idea why this problem occurred?
I think the cause might be the smplx version I install is not correct. The smplx version I installed is 0.1.28. Could you please tell me the smplx version you installed?
![{5KX4LEYJ{_@FPW`W {R4VJ](https://user-images.githubusercontent.com/49779683/206608808-3c1f0a25-803f-419d-9721-cb6a46db1340.png)

**Comment by Zhangjzh** [comment]
I found where the problem is. Thank you anyway.
