### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by 1aq-qa1** [kcyt/SPIFu#7]
Hello, the two links below have expired. Please re-upload them. Thank you very much!

SPIFu trained on Groundtruth SMPL-X (Will follow the SMPL-X pose more closely): https://drive.google.com/file/d/1f6ZTysLvlq23II-pYwwo0lVDbAOHjlq-/view?usp=share_link
SPIFu trained on Predicted SMPL-X (More robust to errors in SMPL-X pose errors): https://drive.google.com/file/d/1gWWMIkrwYQwJaN9KnHBTL2-WTtqmu8wt/view?usp=share_link

**Comment by kcyt** [comment]
I have re-uploaded them (Use the updated links), thanks for letting me know!

**Comment by 1aq-qa1** [comment]
> I have re-uploaded them (Use the updated l> I have re-uploaded them (Use the updated links), thanks for letting me know!

Thanks for your prompt reply. I would like to ask, how long did it take you to train this code?
